/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    CardSpotlight: typeof import('./src/components/ui/card-spotlight.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Editor: typeof import('./src/components/editor/editor.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Listbox: typeof import('primevue/listbox')['default']
    Message: typeof import('primevue/message')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    SystemUpload: typeof import('./src/components/system/system-upload.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    UiAvatar: typeof import('./src/components/ui/ui-avatar.vue')['default']
    UiBufferAvatar: typeof import('./src/components/ui/ui-buffer-avatar.vue')['default']
    UiButton: typeof import('./src/components/ui/ui-button.vue')['default']
    UiTimestamp: typeof import('./src/components/ui/ui-timestamp.vue')['default']
  }
}
