/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedList: typeof import('./src/components/ui/animated-list.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    CardSpotlight: typeof import('./src/components/ui/card-spotlight.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DarkSelect: typeof import('./src/components/dark-select.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    IconField: typeof import('primevue/iconfield')['default']
    'Identity-': typeof import('./src/components/ui/identity-.vue')['default']
    IdentityPanel: typeof import('./src/components/ui/identity-panel.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemClose: typeof import('@renderer/views/system/system-close.vue')['default']
    SystemFullscreen: typeof import('@renderer/views/system/system-fullscreen.vue')['default']
    SystemFullscreenExit: typeof import('@renderer/views/system/system-fullscreen-exit.vue')['default']
    SystemZoomOut: typeof import('@renderer/views/system/system-zoom-out.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    UiAvatar: typeof import('./src/components/ui/ui-avatar.vue')['default']
  }
}
