/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/main': RouteRecordInfo<'/main', '/main', Record<never, never>, Record<never, never>>,
    '/main/': RouteRecordInfo<'/main/', '/main', Record<never, never>, Record<never, never>>,
    '/main/chat': RouteRecordInfo<'/main/chat', '/main/chat', Record<never, never>, Record<never, never>>,
    '/main/chat/': RouteRecordInfo<'/main/chat/', '/main/chat', Record<never, never>, Record<never, never>>,
    '/main/chat/[id]/': RouteRecordInfo<'/main/chat/[id]/', '/main/chat/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/main/folder': RouteRecordInfo<'/main/folder', '/main/folder', Record<never, never>, Record<never, never>>,
  }
}
